### ISSUE TITLE
Invalid client data. Failed to download table

### ISSUE THREAD

**Issue by MiroCillik** [davidesner/keboola-bingads-ex#4]
Klientovi zo dna na den, bez zmeny konfiguracie, extraktor zacal hadzat chybu:

```
com.microsoft.bingads.v11.customermanagement.ApiFault_Exception: Invalid client data. Check the SOAP fault details for more information
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.cxf.interceptor.ClientFaultConverter.processFaultDetail(ClientFaultConverter.java:182)
at org.apache.cxf.interceptor.ClientFaultConverter.handleMessage(ClientFaultConverter.java:82)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:113)
at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessage(SOAPHandlerInterceptor.java:140)
at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessage(SOAPHandlerInterceptor.java:71)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:798)
at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1638)
at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1527)
at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1330)
at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:638)
at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:326)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:279)
at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:138)
at com.sun.proxy.$Proxy104.getAccountsInfo(Unknown Source)
at keboola.bingads.ex.client.Client.getAllAccountsInfo(Client.java:368)
at keboola.bingads.ex.BingAdsRunner.getAndStoreAccounts(BingAdsRunner.java:100)
at keboola.bingads.ex.BingAdsRunner.run(BingAdsRunner.java:70)
at keboola.bingads.ex.Main.main(Main.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
at java.lang.Thread.run(Thread.java:748)
INFO : Downloading bulk data...
INFO : Downloading report queries...
INFO : For Accounts [139083864]
Downloading report data: AdsPerformance.csv
```

A

```
ERROR: Failed to download accounts table!Invalid client data. Check the SOAP fault details for more information
```

**Comment by MiroCillik** [comment]
Od klienta:
"
Ahoj, 
díky za prozkoumání.

Právěže v BingAds neproběhly vůbec žádné změny. Ptal jsem se kolegů, kteří mají Bingads na starosti a prý tam neměnili nic. Takže je nepravděpodobné, že bychom v extractoru měli špatně Account ID. Navíc jsem ID a ostatní položky z konfigurace našel v BingAds a zkontorloval. Všechno by to mělo být dobře.

Martin
"

**Comment by MiroCillik** [comment]
Tak ked som to skusil nasimulovat u seba, tak som okrem podobnej hlasky dostal aj:
```
Message: This version of the Bing Ads API is no longer supported. Please migrate to the latest version of the API. For more details, visit https://go.microsoft.com/fwlink/?linkid=862106.
```

Takze to treba updatnut na novu verziu API. Tato bola deprekovana v Oktobri 2018 a zrejme ju teraz uz uplne vypli.
